/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MailStandaloneRouteImport } from './routes/mail-standalone'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSystemIntelligenceRouteImport } from './routes/_authenticated/system-intelligence'
import { Route as AuthenticatedProductivityRouteImport } from './routes/_authenticated/productivity'
import { Route as AuthenticatedMailRouteImport } from './routes/_authenticated/mail'
import { Route as AuthenticatedDocumentHubRouteImport } from './routes/_authenticated/document-hub'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedProcurementVendorRatesRouteImport } from './routes/_authenticated/procurement/vendor-rates'
import { Route as AuthenticatedProcurementPurchaseOrdersRouteImport } from './routes/_authenticated/procurement/purchase-orders'
import { Route as AuthenticatedProcurementPartnerDirectoryRouteImport } from './routes/_authenticated/procurement/partner-directory'
import { Route as AuthenticatedLogisticsShippingInstructionsRouteImport } from './routes/_authenticated/logistics/shipping-instructions'
import { Route as AuthenticatedLogisticsShipmentsRouteImport } from './routes/_authenticated/logistics/shipments'
import { Route as AuthenticatedLogisticsPackingListRouteImport } from './routes/_authenticated/logistics/packing-list'
import { Route as AuthenticatedLogisticsDndFeeRouteImport } from './routes/_authenticated/logistics/dnd-fee'
import { Route as AuthenticatedLogisticsCargoTrackingRouteImport } from './routes/_authenticated/logistics/cargo-tracking'
import { Route as AuthenticatedFinanceVendorBillsRouteImport } from './routes/_authenticated/finance/vendor-bills'
import { Route as AuthenticatedFinanceOverviewRouteImport } from './routes/_authenticated/finance/overview'
import { Route as AuthenticatedFinanceGeneralLedgerRouteImport } from './routes/_authenticated/finance/general-ledger'
import { Route as AuthenticatedFinanceCostAccrualsRouteImport } from './routes/_authenticated/finance/cost-accruals'
import { Route as AuthenticatedFinanceClientInvoicingRouteImport } from './routes/_authenticated/finance/client-invoicing'
import { Route as AuthenticatedFinanceClientInvoicesRouteImport } from './routes/_authenticated/finance/client-invoices'
import { Route as AuthenticatedFinanceAccountsReceivableRouteImport } from './routes/_authenticated/finance/accounts-receivable'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedComplianceTradeLicensesRouteImport } from './routes/_authenticated/compliance/trade-licenses'
import { Route as AuthenticatedComplianceDutyTariffsRouteImport } from './routes/_authenticated/compliance/duty-tariffs'
import { Route as AuthenticatedComplianceCustomsDeclarationsRouteImport } from './routes/_authenticated/compliance/customs-declarations'
import { Route as AuthenticatedCommercialServiceQuotationsRouteImport } from './routes/_authenticated/commercial/service-quotations'
import { Route as AuthenticatedCommercialClientContractsRouteImport } from './routes/_authenticated/commercial/client-contracts'
import { Route as AuthenticatedCommercialClientAccountsRouteImport } from './routes/_authenticated/commercial/client-accounts'

const MailStandaloneRoute = MailStandaloneRouteImport.update({
  id: '/mail-standalone',
  path: '/mail-standalone',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemIntelligenceRoute =
  AuthenticatedSystemIntelligenceRouteImport.update({
    id: '/system-intelligence',
    path: '/system-intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductivityRoute =
  AuthenticatedProductivityRouteImport.update({
    id: '/productivity',
    path: '/productivity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMailRoute = AuthenticatedMailRouteImport.update({
  id: '/mail',
  path: '/mail',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentHubRoute =
  AuthenticatedDocumentHubRouteImport.update({
    id: '/document-hub',
    path: '/document-hub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedProcurementVendorRatesRoute =
  AuthenticatedProcurementVendorRatesRouteImport.update({
    id: '/procurement/vendor-rates',
    path: '/procurement/vendor-rates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementPurchaseOrdersRoute =
  AuthenticatedProcurementPurchaseOrdersRouteImport.update({
    id: '/procurement/purchase-orders',
    path: '/procurement/purchase-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProcurementPartnerDirectoryRoute =
  AuthenticatedProcurementPartnerDirectoryRouteImport.update({
    id: '/procurement/partner-directory',
    path: '/procurement/partner-directory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogisticsShippingInstructionsRoute =
  AuthenticatedLogisticsShippingInstructionsRouteImport.update({
    id: '/logistics/shipping-instructions',
    path: '/logistics/shipping-instructions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogisticsShipmentsRoute =
  AuthenticatedLogisticsShipmentsRouteImport.update({
    id: '/logistics/shipments',
    path: '/logistics/shipments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogisticsPackingListRoute =
  AuthenticatedLogisticsPackingListRouteImport.update({
    id: '/logistics/packing-list',
    path: '/logistics/packing-list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogisticsDndFeeRoute =
  AuthenticatedLogisticsDndFeeRouteImport.update({
    id: '/logistics/dnd-fee',
    path: '/logistics/dnd-fee',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogisticsCargoTrackingRoute =
  AuthenticatedLogisticsCargoTrackingRouteImport.update({
    id: '/logistics/cargo-tracking',
    path: '/logistics/cargo-tracking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceVendorBillsRoute =
  AuthenticatedFinanceVendorBillsRouteImport.update({
    id: '/finance/vendor-bills',
    path: '/finance/vendor-bills',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceOverviewRoute =
  AuthenticatedFinanceOverviewRouteImport.update({
    id: '/finance/overview',
    path: '/finance/overview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceGeneralLedgerRoute =
  AuthenticatedFinanceGeneralLedgerRouteImport.update({
    id: '/finance/general-ledger',
    path: '/finance/general-ledger',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceCostAccrualsRoute =
  AuthenticatedFinanceCostAccrualsRouteImport.update({
    id: '/finance/cost-accruals',
    path: '/finance/cost-accruals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceClientInvoicingRoute =
  AuthenticatedFinanceClientInvoicingRouteImport.update({
    id: '/finance/client-invoicing',
    path: '/finance/client-invoicing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceClientInvoicesRoute =
  AuthenticatedFinanceClientInvoicesRouteImport.update({
    id: '/finance/client-invoices',
    path: '/finance/client-invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceAccountsReceivableRoute =
  AuthenticatedFinanceAccountsReceivableRouteImport.update({
    id: '/finance/accounts-receivable',
    path: '/finance/accounts-receivable',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceTradeLicensesRoute =
  AuthenticatedComplianceTradeLicensesRouteImport.update({
    id: '/compliance/trade-licenses',
    path: '/compliance/trade-licenses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceDutyTariffsRoute =
  AuthenticatedComplianceDutyTariffsRouteImport.update({
    id: '/compliance/duty-tariffs',
    path: '/compliance/duty-tariffs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComplianceCustomsDeclarationsRoute =
  AuthenticatedComplianceCustomsDeclarationsRouteImport.update({
    id: '/compliance/customs-declarations',
    path: '/compliance/customs-declarations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercialServiceQuotationsRoute =
  AuthenticatedCommercialServiceQuotationsRouteImport.update({
    id: '/commercial/service-quotations',
    path: '/commercial/service-quotations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercialClientContractsRoute =
  AuthenticatedCommercialClientContractsRouteImport.update({
    id: '/commercial/client-contracts',
    path: '/commercial/client-contracts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercialClientAccountsRoute =
  AuthenticatedCommercialClientAccountsRouteImport.update({
    id: '/commercial/client-accounts',
    path: '/commercial/client-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/mail-standalone': typeof MailStandaloneRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/document-hub': typeof AuthenticatedDocumentHubRoute
  '/mail': typeof AuthenticatedMailRoute
  '/productivity': typeof AuthenticatedProductivityRoute
  '/system-intelligence': typeof AuthenticatedSystemIntelligenceRoute
  '/': typeof AuthenticatedIndexRoute
  '/commercial/client-accounts': typeof AuthenticatedCommercialClientAccountsRoute
  '/commercial/client-contracts': typeof AuthenticatedCommercialClientContractsRoute
  '/commercial/service-quotations': typeof AuthenticatedCommercialServiceQuotationsRoute
  '/compliance/customs-declarations': typeof AuthenticatedComplianceCustomsDeclarationsRoute
  '/compliance/duty-tariffs': typeof AuthenticatedComplianceDutyTariffsRoute
  '/compliance/trade-licenses': typeof AuthenticatedComplianceTradeLicensesRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/finance/accounts-receivable': typeof AuthenticatedFinanceAccountsReceivableRoute
  '/finance/client-invoices': typeof AuthenticatedFinanceClientInvoicesRoute
  '/finance/client-invoicing': typeof AuthenticatedFinanceClientInvoicingRoute
  '/finance/cost-accruals': typeof AuthenticatedFinanceCostAccrualsRoute
  '/finance/general-ledger': typeof AuthenticatedFinanceGeneralLedgerRoute
  '/finance/overview': typeof AuthenticatedFinanceOverviewRoute
  '/finance/vendor-bills': typeof AuthenticatedFinanceVendorBillsRoute
  '/logistics/cargo-tracking': typeof AuthenticatedLogisticsCargoTrackingRoute
  '/logistics/dnd-fee': typeof AuthenticatedLogisticsDndFeeRoute
  '/logistics/packing-list': typeof AuthenticatedLogisticsPackingListRoute
  '/logistics/shipments': typeof AuthenticatedLogisticsShipmentsRoute
  '/logistics/shipping-instructions': typeof AuthenticatedLogisticsShippingInstructionsRoute
  '/procurement/partner-directory': typeof AuthenticatedProcurementPartnerDirectoryRoute
  '/procurement/purchase-orders': typeof AuthenticatedProcurementPurchaseOrdersRoute
  '/procurement/vendor-rates': typeof AuthenticatedProcurementVendorRatesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/chat': typeof ChatRoute
  '/mail-standalone': typeof MailStandaloneRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/document-hub': typeof AuthenticatedDocumentHubRoute
  '/mail': typeof AuthenticatedMailRoute
  '/productivity': typeof AuthenticatedProductivityRoute
  '/system-intelligence': typeof AuthenticatedSystemIntelligenceRoute
  '/': typeof AuthenticatedIndexRoute
  '/commercial/client-accounts': typeof AuthenticatedCommercialClientAccountsRoute
  '/commercial/client-contracts': typeof AuthenticatedCommercialClientContractsRoute
  '/commercial/service-quotations': typeof AuthenticatedCommercialServiceQuotationsRoute
  '/compliance/customs-declarations': typeof AuthenticatedComplianceCustomsDeclarationsRoute
  '/compliance/duty-tariffs': typeof AuthenticatedComplianceDutyTariffsRoute
  '/compliance/trade-licenses': typeof AuthenticatedComplianceTradeLicensesRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/finance/accounts-receivable': typeof AuthenticatedFinanceAccountsReceivableRoute
  '/finance/client-invoices': typeof AuthenticatedFinanceClientInvoicesRoute
  '/finance/client-invoicing': typeof AuthenticatedFinanceClientInvoicingRoute
  '/finance/cost-accruals': typeof AuthenticatedFinanceCostAccrualsRoute
  '/finance/general-ledger': typeof AuthenticatedFinanceGeneralLedgerRoute
  '/finance/overview': typeof AuthenticatedFinanceOverviewRoute
  '/finance/vendor-bills': typeof AuthenticatedFinanceVendorBillsRoute
  '/logistics/cargo-tracking': typeof AuthenticatedLogisticsCargoTrackingRoute
  '/logistics/dnd-fee': typeof AuthenticatedLogisticsDndFeeRoute
  '/logistics/packing-list': typeof AuthenticatedLogisticsPackingListRoute
  '/logistics/shipments': typeof AuthenticatedLogisticsShipmentsRoute
  '/logistics/shipping-instructions': typeof AuthenticatedLogisticsShippingInstructionsRoute
  '/procurement/partner-directory': typeof AuthenticatedProcurementPartnerDirectoryRoute
  '/procurement/purchase-orders': typeof AuthenticatedProcurementPurchaseOrdersRoute
  '/procurement/vendor-rates': typeof AuthenticatedProcurementVendorRatesRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/chat': typeof ChatRoute
  '/mail-standalone': typeof MailStandaloneRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/document-hub': typeof AuthenticatedDocumentHubRoute
  '/_authenticated/mail': typeof AuthenticatedMailRoute
  '/_authenticated/productivity': typeof AuthenticatedProductivityRoute
  '/_authenticated/system-intelligence': typeof AuthenticatedSystemIntelligenceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/commercial/client-accounts': typeof AuthenticatedCommercialClientAccountsRoute
  '/_authenticated/commercial/client-contracts': typeof AuthenticatedCommercialClientContractsRoute
  '/_authenticated/commercial/service-quotations': typeof AuthenticatedCommercialServiceQuotationsRoute
  '/_authenticated/compliance/customs-declarations': typeof AuthenticatedComplianceCustomsDeclarationsRoute
  '/_authenticated/compliance/duty-tariffs': typeof AuthenticatedComplianceDutyTariffsRoute
  '/_authenticated/compliance/trade-licenses': typeof AuthenticatedComplianceTradeLicensesRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/finance/accounts-receivable': typeof AuthenticatedFinanceAccountsReceivableRoute
  '/_authenticated/finance/client-invoices': typeof AuthenticatedFinanceClientInvoicesRoute
  '/_authenticated/finance/client-invoicing': typeof AuthenticatedFinanceClientInvoicingRoute
  '/_authenticated/finance/cost-accruals': typeof AuthenticatedFinanceCostAccrualsRoute
  '/_authenticated/finance/general-ledger': typeof AuthenticatedFinanceGeneralLedgerRoute
  '/_authenticated/finance/overview': typeof AuthenticatedFinanceOverviewRoute
  '/_authenticated/finance/vendor-bills': typeof AuthenticatedFinanceVendorBillsRoute
  '/_authenticated/logistics/cargo-tracking': typeof AuthenticatedLogisticsCargoTrackingRoute
  '/_authenticated/logistics/dnd-fee': typeof AuthenticatedLogisticsDndFeeRoute
  '/_authenticated/logistics/packing-list': typeof AuthenticatedLogisticsPackingListRoute
  '/_authenticated/logistics/shipments': typeof AuthenticatedLogisticsShipmentsRoute
  '/_authenticated/logistics/shipping-instructions': typeof AuthenticatedLogisticsShippingInstructionsRoute
  '/_authenticated/procurement/partner-directory': typeof AuthenticatedProcurementPartnerDirectoryRoute
  '/_authenticated/procurement/purchase-orders': typeof AuthenticatedProcurementPurchaseOrdersRoute
  '/_authenticated/procurement/vendor-rates': typeof AuthenticatedProcurementVendorRatesRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/chat'
    | '/mail-standalone'
    | '/settings'
    | '/clerk/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/analytics'
    | '/document-hub'
    | '/mail'
    | '/productivity'
    | '/system-intelligence'
    | '/'
    | '/commercial/client-accounts'
    | '/commercial/client-contracts'
    | '/commercial/service-quotations'
    | '/compliance/customs-declarations'
    | '/compliance/duty-tariffs'
    | '/compliance/trade-licenses'
    | '/errors/$error'
    | '/finance/accounts-receivable'
    | '/finance/client-invoices'
    | '/finance/client-invoicing'
    | '/finance/cost-accruals'
    | '/finance/general-ledger'
    | '/finance/overview'
    | '/finance/vendor-bills'
    | '/logistics/cargo-tracking'
    | '/logistics/dnd-fee'
    | '/logistics/packing-list'
    | '/logistics/shipments'
    | '/logistics/shipping-instructions'
    | '/procurement/partner-directory'
    | '/procurement/purchase-orders'
    | '/procurement/vendor-rates'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings/'
    | '/tasks'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/chat'
    | '/mail-standalone'
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/analytics'
    | '/document-hub'
    | '/mail'
    | '/productivity'
    | '/system-intelligence'
    | '/'
    | '/commercial/client-accounts'
    | '/commercial/client-contracts'
    | '/commercial/service-quotations'
    | '/compliance/customs-declarations'
    | '/compliance/duty-tariffs'
    | '/compliance/trade-licenses'
    | '/errors/$error'
    | '/finance/accounts-receivable'
    | '/finance/client-invoices'
    | '/finance/client-invoicing'
    | '/finance/cost-accruals'
    | '/finance/general-ledger'
    | '/finance/overview'
    | '/finance/vendor-bills'
    | '/logistics/cargo-tracking'
    | '/logistics/dnd-fee'
    | '/logistics/packing-list'
    | '/logistics/shipments'
    | '/logistics/shipping-instructions'
    | '/procurement/partner-directory'
    | '/procurement/purchase-orders'
    | '/procurement/vendor-rates'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/chat'
    | '/mail-standalone'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/analytics'
    | '/_authenticated/document-hub'
    | '/_authenticated/mail'
    | '/_authenticated/productivity'
    | '/_authenticated/system-intelligence'
    | '/_authenticated/'
    | '/_authenticated/commercial/client-accounts'
    | '/_authenticated/commercial/client-contracts'
    | '/_authenticated/commercial/service-quotations'
    | '/_authenticated/compliance/customs-declarations'
    | '/_authenticated/compliance/duty-tariffs'
    | '/_authenticated/compliance/trade-licenses'
    | '/_authenticated/errors/$error'
    | '/_authenticated/finance/accounts-receivable'
    | '/_authenticated/finance/client-invoices'
    | '/_authenticated/finance/client-invoicing'
    | '/_authenticated/finance/cost-accruals'
    | '/_authenticated/finance/general-ledger'
    | '/_authenticated/finance/overview'
    | '/_authenticated/finance/vendor-bills'
    | '/_authenticated/logistics/cargo-tracking'
    | '/_authenticated/logistics/dnd-fee'
    | '/_authenticated/logistics/packing-list'
    | '/_authenticated/logistics/shipments'
    | '/_authenticated/logistics/shipping-instructions'
    | '/_authenticated/procurement/partner-directory'
    | '/_authenticated/procurement/purchase-orders'
    | '/_authenticated/procurement/vendor-rates'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  ChatRoute: typeof ChatRoute
  MailStandaloneRoute: typeof MailStandaloneRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mail-standalone': {
      id: '/mail-standalone'
      path: '/mail-standalone'
      fullPath: '/mail-standalone'
      preLoaderRoute: typeof MailStandaloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-intelligence': {
      id: '/_authenticated/system-intelligence'
      path: '/system-intelligence'
      fullPath: '/system-intelligence'
      preLoaderRoute: typeof AuthenticatedSystemIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productivity': {
      id: '/_authenticated/productivity'
      path: '/productivity'
      fullPath: '/productivity'
      preLoaderRoute: typeof AuthenticatedProductivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mail': {
      id: '/_authenticated/mail'
      path: '/mail'
      fullPath: '/mail'
      preLoaderRoute: typeof AuthenticatedMailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document-hub': {
      id: '/_authenticated/document-hub'
      path: '/document-hub'
      fullPath: '/document-hub'
      preLoaderRoute: typeof AuthenticatedDocumentHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: '/'
      fullPath: '/clerk/'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/procurement/vendor-rates': {
      id: '/_authenticated/procurement/vendor-rates'
      path: '/procurement/vendor-rates'
      fullPath: '/procurement/vendor-rates'
      preLoaderRoute: typeof AuthenticatedProcurementVendorRatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/purchase-orders': {
      id: '/_authenticated/procurement/purchase-orders'
      path: '/procurement/purchase-orders'
      fullPath: '/procurement/purchase-orders'
      preLoaderRoute: typeof AuthenticatedProcurementPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement/partner-directory': {
      id: '/_authenticated/procurement/partner-directory'
      path: '/procurement/partner-directory'
      fullPath: '/procurement/partner-directory'
      preLoaderRoute: typeof AuthenticatedProcurementPartnerDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistics/shipping-instructions': {
      id: '/_authenticated/logistics/shipping-instructions'
      path: '/logistics/shipping-instructions'
      fullPath: '/logistics/shipping-instructions'
      preLoaderRoute: typeof AuthenticatedLogisticsShippingInstructionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistics/shipments': {
      id: '/_authenticated/logistics/shipments'
      path: '/logistics/shipments'
      fullPath: '/logistics/shipments'
      preLoaderRoute: typeof AuthenticatedLogisticsShipmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistics/packing-list': {
      id: '/_authenticated/logistics/packing-list'
      path: '/logistics/packing-list'
      fullPath: '/logistics/packing-list'
      preLoaderRoute: typeof AuthenticatedLogisticsPackingListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistics/dnd-fee': {
      id: '/_authenticated/logistics/dnd-fee'
      path: '/logistics/dnd-fee'
      fullPath: '/logistics/dnd-fee'
      preLoaderRoute: typeof AuthenticatedLogisticsDndFeeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logistics/cargo-tracking': {
      id: '/_authenticated/logistics/cargo-tracking'
      path: '/logistics/cargo-tracking'
      fullPath: '/logistics/cargo-tracking'
      preLoaderRoute: typeof AuthenticatedLogisticsCargoTrackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/vendor-bills': {
      id: '/_authenticated/finance/vendor-bills'
      path: '/finance/vendor-bills'
      fullPath: '/finance/vendor-bills'
      preLoaderRoute: typeof AuthenticatedFinanceVendorBillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/overview': {
      id: '/_authenticated/finance/overview'
      path: '/finance/overview'
      fullPath: '/finance/overview'
      preLoaderRoute: typeof AuthenticatedFinanceOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/general-ledger': {
      id: '/_authenticated/finance/general-ledger'
      path: '/finance/general-ledger'
      fullPath: '/finance/general-ledger'
      preLoaderRoute: typeof AuthenticatedFinanceGeneralLedgerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/cost-accruals': {
      id: '/_authenticated/finance/cost-accruals'
      path: '/finance/cost-accruals'
      fullPath: '/finance/cost-accruals'
      preLoaderRoute: typeof AuthenticatedFinanceCostAccrualsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/client-invoicing': {
      id: '/_authenticated/finance/client-invoicing'
      path: '/finance/client-invoicing'
      fullPath: '/finance/client-invoicing'
      preLoaderRoute: typeof AuthenticatedFinanceClientInvoicingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/client-invoices': {
      id: '/_authenticated/finance/client-invoices'
      path: '/finance/client-invoices'
      fullPath: '/finance/client-invoices'
      preLoaderRoute: typeof AuthenticatedFinanceClientInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/accounts-receivable': {
      id: '/_authenticated/finance/accounts-receivable'
      path: '/finance/accounts-receivable'
      fullPath: '/finance/accounts-receivable'
      preLoaderRoute: typeof AuthenticatedFinanceAccountsReceivableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/trade-licenses': {
      id: '/_authenticated/compliance/trade-licenses'
      path: '/compliance/trade-licenses'
      fullPath: '/compliance/trade-licenses'
      preLoaderRoute: typeof AuthenticatedComplianceTradeLicensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/duty-tariffs': {
      id: '/_authenticated/compliance/duty-tariffs'
      path: '/compliance/duty-tariffs'
      fullPath: '/compliance/duty-tariffs'
      preLoaderRoute: typeof AuthenticatedComplianceDutyTariffsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance/customs-declarations': {
      id: '/_authenticated/compliance/customs-declarations'
      path: '/compliance/customs-declarations'
      fullPath: '/compliance/customs-declarations'
      preLoaderRoute: typeof AuthenticatedComplianceCustomsDeclarationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial/service-quotations': {
      id: '/_authenticated/commercial/service-quotations'
      path: '/commercial/service-quotations'
      fullPath: '/commercial/service-quotations'
      preLoaderRoute: typeof AuthenticatedCommercialServiceQuotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial/client-contracts': {
      id: '/_authenticated/commercial/client-contracts'
      path: '/commercial/client-contracts'
      fullPath: '/commercial/client-contracts'
      preLoaderRoute: typeof AuthenticatedCommercialClientContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial/client-accounts': {
      id: '/_authenticated/commercial/client-accounts'
      path: '/commercial/client-accounts'
      fullPath: '/commercial/client-accounts'
      preLoaderRoute: typeof AuthenticatedCommercialClientAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDocumentHubRoute: typeof AuthenticatedDocumentHubRoute
  AuthenticatedMailRoute: typeof AuthenticatedMailRoute
  AuthenticatedProductivityRoute: typeof AuthenticatedProductivityRoute
  AuthenticatedSystemIntelligenceRoute: typeof AuthenticatedSystemIntelligenceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCommercialClientAccountsRoute: typeof AuthenticatedCommercialClientAccountsRoute
  AuthenticatedCommercialClientContractsRoute: typeof AuthenticatedCommercialClientContractsRoute
  AuthenticatedCommercialServiceQuotationsRoute: typeof AuthenticatedCommercialServiceQuotationsRoute
  AuthenticatedComplianceCustomsDeclarationsRoute: typeof AuthenticatedComplianceCustomsDeclarationsRoute
  AuthenticatedComplianceDutyTariffsRoute: typeof AuthenticatedComplianceDutyTariffsRoute
  AuthenticatedComplianceTradeLicensesRoute: typeof AuthenticatedComplianceTradeLicensesRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedFinanceAccountsReceivableRoute: typeof AuthenticatedFinanceAccountsReceivableRoute
  AuthenticatedFinanceClientInvoicesRoute: typeof AuthenticatedFinanceClientInvoicesRoute
  AuthenticatedFinanceClientInvoicingRoute: typeof AuthenticatedFinanceClientInvoicingRoute
  AuthenticatedFinanceCostAccrualsRoute: typeof AuthenticatedFinanceCostAccrualsRoute
  AuthenticatedFinanceGeneralLedgerRoute: typeof AuthenticatedFinanceGeneralLedgerRoute
  AuthenticatedFinanceOverviewRoute: typeof AuthenticatedFinanceOverviewRoute
  AuthenticatedFinanceVendorBillsRoute: typeof AuthenticatedFinanceVendorBillsRoute
  AuthenticatedLogisticsCargoTrackingRoute: typeof AuthenticatedLogisticsCargoTrackingRoute
  AuthenticatedLogisticsDndFeeRoute: typeof AuthenticatedLogisticsDndFeeRoute
  AuthenticatedLogisticsPackingListRoute: typeof AuthenticatedLogisticsPackingListRoute
  AuthenticatedLogisticsShipmentsRoute: typeof AuthenticatedLogisticsShipmentsRoute
  AuthenticatedLogisticsShippingInstructionsRoute: typeof AuthenticatedLogisticsShippingInstructionsRoute
  AuthenticatedProcurementPartnerDirectoryRoute: typeof AuthenticatedProcurementPartnerDirectoryRoute
  AuthenticatedProcurementPurchaseOrdersRoute: typeof AuthenticatedProcurementPurchaseOrdersRoute
  AuthenticatedProcurementVendorRatesRoute: typeof AuthenticatedProcurementVendorRatesRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDocumentHubRoute: AuthenticatedDocumentHubRoute,
  AuthenticatedMailRoute: AuthenticatedMailRoute,
  AuthenticatedProductivityRoute: AuthenticatedProductivityRoute,
  AuthenticatedSystemIntelligenceRoute: AuthenticatedSystemIntelligenceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCommercialClientAccountsRoute:
    AuthenticatedCommercialClientAccountsRoute,
  AuthenticatedCommercialClientContractsRoute:
    AuthenticatedCommercialClientContractsRoute,
  AuthenticatedCommercialServiceQuotationsRoute:
    AuthenticatedCommercialServiceQuotationsRoute,
  AuthenticatedComplianceCustomsDeclarationsRoute:
    AuthenticatedComplianceCustomsDeclarationsRoute,
  AuthenticatedComplianceDutyTariffsRoute:
    AuthenticatedComplianceDutyTariffsRoute,
  AuthenticatedComplianceTradeLicensesRoute:
    AuthenticatedComplianceTradeLicensesRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedFinanceAccountsReceivableRoute:
    AuthenticatedFinanceAccountsReceivableRoute,
  AuthenticatedFinanceClientInvoicesRoute:
    AuthenticatedFinanceClientInvoicesRoute,
  AuthenticatedFinanceClientInvoicingRoute:
    AuthenticatedFinanceClientInvoicingRoute,
  AuthenticatedFinanceCostAccrualsRoute: AuthenticatedFinanceCostAccrualsRoute,
  AuthenticatedFinanceGeneralLedgerRoute:
    AuthenticatedFinanceGeneralLedgerRoute,
  AuthenticatedFinanceOverviewRoute: AuthenticatedFinanceOverviewRoute,
  AuthenticatedFinanceVendorBillsRoute: AuthenticatedFinanceVendorBillsRoute,
  AuthenticatedLogisticsCargoTrackingRoute:
    AuthenticatedLogisticsCargoTrackingRoute,
  AuthenticatedLogisticsDndFeeRoute: AuthenticatedLogisticsDndFeeRoute,
  AuthenticatedLogisticsPackingListRoute:
    AuthenticatedLogisticsPackingListRoute,
  AuthenticatedLogisticsShipmentsRoute: AuthenticatedLogisticsShipmentsRoute,
  AuthenticatedLogisticsShippingInstructionsRoute:
    AuthenticatedLogisticsShippingInstructionsRoute,
  AuthenticatedProcurementPartnerDirectoryRoute:
    AuthenticatedProcurementPartnerDirectoryRoute,
  AuthenticatedProcurementPurchaseOrdersRoute:
    AuthenticatedProcurementPurchaseOrdersRoute,
  AuthenticatedProcurementVendorRatesRoute:
    AuthenticatedProcurementVendorRatesRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  ChatRoute: ChatRoute,
  MailStandaloneRoute: MailStandaloneRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
